apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hbdk4lz7i-java-springboot 
  janus-idp.io/tekton: hbdk4lz7i-java-springboot
  backstage.io/kubernetes-id: hbdk4lz7i-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hbdk4lz7i-java-springboot
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml